### ISSUE TITLE
Kegbot at http address throws errors

### ISSUE THREAD

**Issue by myrison** [patfreeman/alexa-lambda-kegbot#5]
Hi Pat - Thanks for uploading v2.  Although I don't have it working yet, the new additions look like a huge leap forward.

I previously had v1 working fine with no issues, but as I've moved to v2, here is the error I'm getting from the Lamda function.

I'll do some digging to see if I can figure out where this is being generated, but I wanted to raise the issue in the meantime to see if you can pinpoint it faster than I can.

Thanks.

Error logs:

2020-06-10T02:55:21.783Z	2549fdc9-2bbb-46be-98c0-c6c23a4c5a13	INFO	Error handled: Protocol "http:" not supported. Expected "https:"

2020-06-10T02:55:21.784Z	2549fdc9-2bbb-46be-98c0-c6c23a4c5a13	INFO	Error stack: TypeError [ERR_INVALID_PROTOCOL]: Protocol "http:" not supported. Expected "https:"
    at new ClientRequest (_http_client.js:152:11)
    at request (https.js:314:10)
    at Object.get (https.js:318:15)
    at /var/task/lib/kegbot.js:32:8
    at new Promise (<anonymous>)
    at Object.getCurrentKegs (/var/task/lib/kegbot.js:30:10)
    at Object.handle (/var/task/index.js:45:31)
    at GenericHandlerAdapter.<anonymous> (/var/task/node_modules/ask-sdk-core/node_modules/ask-sdk-runtime/dist/dispatcher/request/handler/GenericHandlerAdapter.js:63:47)
    at step (/var/task/node_modules/ask-sdk-core/node_modules/ask-sdk-runtime/dist/dispatcher/request/handler/GenericHandlerAdapter.js:44:23)
    at Object.next (/var/task/node_modules/ask-sdk-core/node_modules/ask-sdk-runtime/dist/dispatcher/request/handler/GenericHandlerAdapter.js:25:53)

**Comment by patfreeman** [comment]
I was worried that might happen. I think we just need to switch between https and http. i'll take a look.

**Comment by myrison** [comment]
Thanks for the quick reply.  After following the bouncing ball on the errors a bit, if I had to guess, the problem looks like it's in lib/kegbot.js.  I'm not sure how to fix it without breaking something else, so when you have time, please let me know if that's the culprit or something else.  Cheers.

**Comment by patfreeman** [comment]
Should be fixed on master now. Test it out and let me know.

**Comment by myrison** [comment]
Bingo, fixed it right up. Thanks!
